# Generated by Django 2.1.5 on 2019-02-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190207_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_req_1',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_req_2',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_req_3',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_req_4',
            field=models.CharField(default='', max_length=300),
        ),
    ]
