# Generated by Django 2.1.5 on 2019-02-06 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_application',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='job_application',
            name='job_seeker_mail',
        ),
        migrations.DeleteModel(
            name='job_application',
        ),
    ]
