# Generated by Django 2.1.5 on 2019-02-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190203_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_seeker',
            name='id',
        ),
        migrations.AlterField(
            model_name='job_seeker',
            name='email',
            field=models.EmailField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
