# Generated by Django 2.1.5 on 2019-02-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_job_seeker_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_seeker',
            name='resume',
            field=models.CharField(max_length=300),
        ),
    ]
