# Generated by Django 2.1.5 on 2019-02-03 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0002_auto_20190203_2051'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='recruier',
            new_name='recruiter',
        ),
    ]
