# Generated by Django 2.1.5 on 2019-02-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0004_auto_20190205_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_location',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='job_req_1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='job_req_2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='job_req_3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='job_req_4',
            field=models.CharField(default='', max_length=50),
        ),
    ]
