# Generated by Django 2.1.5 on 2019-02-07 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190207_0732'),
        ('recruiter', '0005_auto_20190205_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_poster',
        ),
        migrations.DeleteModel(
            name='job',
        ),
    ]
